@url_dev=http://localhost:3055/v1/api

POST {{url_dev}}/shop/sign-up
Content-Type: application/json
x-api-key: baonguyen

{
    "name": "Bao nguyen",
    "email" : "example123@gmail.com",
    "password" : "123123"
}


###
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: baonguyen

{
    "email" : "example123@gmail.com",
    "password" : "123123"
}

###
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a2f815c2587fef38033194
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmEyZjgxNWMyNTg3ZmVmMzgwMzMxOTQiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIxOTU2ODc5LCJleHAiOjE3MjIxMjk2Nzl9.kPNhG_lMGRYIIWGjSjL0ICyzbx7lMq7oQr8TjxknS5g