@url_dev=http://localhost:3055/v1/api

POST {{url_dev}}/shop/sign-up
Content-Type: application/json
x-api-key: baonguyen

{
    "name": "Bao nguyen",
    "email" : "example123@gmail.com",
    "password" : "123123"
}


###
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: baonguyen

{
    "email" : "example123@gmail.com",
    "password" : "123123"
}

###
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a2f815c2587fef38033194
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmEyZjgxNWMyNTg3ZmVmMzgwMzMxOTQiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIxOTU4MjQ1LCJleHAiOjE3MjIxMzEwNDV9.7mo_js6-0kuHawDtI8wb_8_ccgz8bqY4Lgw5hu9aNUQ

###
POST {{url_dev}}/shop/handRefeshToken
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a31ae40e5d5b78e6fd8a58
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmEzMWFlNDBlNWQ1Yjc4ZTZmZDhhNTgiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIxOTY1MzM0LCJleHAiOjE3MjIxMzgxMzR9.BzMN_0xGgCcyVX-T24fzOJXrPg80G7E91JMc_V1nrlQ

{
    "refeshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmEzMWFlNDBlNWQ1Yjc4ZTZmZDhhNTgiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIxOTY1MzM0LCJleHAiOjE3MjI1NzAxMzR9._0fg4yV6KOlYT7rL53FC5n0TpnK34yHYrStHMk5zkv4"
}

###
POST {{url_dev}}/product/
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a31d140e5d5b78e6fd8a6e
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmEzMWQxNDBlNWQ1Yjc4ZTZmZDhhNmUiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIxOTg1MTQ1LCJleHAiOjE3MjIxNTc5NDV9.vJJkZUjO7uJnd0W7yx6vv97veHtNovJbvZ4clbEJTcM

{
    "product_name": "day chuyen chu dai bi",
    "product_thumb": "example",
    "product_description": "day chuyen chu dai bi",
    "product_price": 2000,
    "product_quantity": 10,
    "product_type": "Clothing",
    "product_shop": "66a31ae40e5d5b78e6fd8a58",
    "product_attributes": {"brand": "Sxx", "size": "XXL", "material": "String"}
}