@url_dev=http://localhost:3055/v1/api
@Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzI0MzE0NjkzLCJleHAiOjE3MjQ0ODc0OTN9.8Yfbd-N9H8l5iKKehJAh3Rhz4tU4v4GWoGRyORbDdTo
@ApiKey=baonguyen
@ClientId=66a5b830837f0697ccebba73


### Add product to cart
POST {{url_dev}}/cart/
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

{
    "product_id" : "66b1c3e47b7e4a56e762a4ec",
    "product_price": 2000,
    "cart_quantity": 1,
    "shop_id": "66a5b830837f0697ccebba73"
}


### Get cart list by userId
GET {{url_dev}}/cart/
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

### delete item in cart by product id [user]
DELETE  {{url_dev}}/cart/
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

{
    "product_id": "66a5bfcfe7aea184f1184c16"
}

### update product quantity in cart
PATCH {{url_dev}}/cart/update-quantity
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

{
    "shop_order_ids": [
        {
            "shop_id": "66a5b830837f0697ccebba73",
            "item_products": [
                {
                    "quantity": 2,
                    "price": 200,
                    "old_quantity": 10,
                    "shopId": "66a5b830837f0697ccebba73",
                    "product_id": "66b1c3e47b7e4a56e762a4ec"
                }
            ],
            "version": "12"
        }
    ]
}
