@url_dev=http://localhost:3055/v1/api
@Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzI1MTYwMjk2LCJleHAiOjE3MjUzMzMwOTZ9.BwE-TYXUUZ495OkcQfxLX2Ts2olAjOphcOpRzDQsk3g
@ApiKey=baonguyen
@ClientId=66a5b830837f0697ccebba73

### Add new discount by Shop
POST {{url_dev}}/comment/create
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

{
    "productId": "66a5bfcfe7aea184f1184c16",
    "content": "hello 1.2.2",
    "parentCommentId": "66d4242b10cdc5b18a0aa436"
}