@url_dev=http://localhost:3055/v1/api
@Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIzMjc2OTM3LCJleHAiOjE3MjM0NDk3Mzd9.sykHb7Mhg0imM0WNls-qt7NFrIPUkAIzLVIdcKZqSvI
@ApiKey=baonguyen
@ClientId=66a5b830837f0697ccebba73

### Add new discount by Shop
POST {{url_dev}}/discount/
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

{
    "discount_name": "flash sale 8/8 siuu salee",
    "discount_description": "flash sale 8/8 siuu salee",
    "discount_type": "fixed_amount",
    "discount_value": 100000, 
    "discount_code": "VNSHOPEE_SALE", 
    "discount_start_date": "2024-8-10",
    "discount_end_date": "2024-9-10",
    "discount_max_uses": 100, 
    "discount_max_per_users": 1,
    "discount_min_order_value": 10000,
    "discount_applies_to": "all",
    "discount_product_ids": ["66a5bfcfe7aea184f1184c16"]
}