@url_dev=http://localhost:3055/v1/api
@Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzI4NzE2MjI0LCJleHAiOjE3Mjg4ODkwMjR9.pezsDTb9_1JfOhO2OtEMJWAhu_ql3kKAcH6kg3ErBp8
@ApiKey=baonguyen
@ClientId=66a5b830837f0697ccebba73

### Create new Comment by user
GET {{url_dev}}/notification/
Content-Type: application/json
x-api-key: {{ApiKey}}
x-client-id: {{ClientId}}
authorization:{{Authorization}}

{
    "type": "ALL",
    "receiverId": "66a5b830837f0697ccebba73",
    "isRead": false
}
