@url_dev=http://localhost:3055/v1/api


###
POST {{url_dev}}/product/
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzI4NzE2MjI0LCJleHAiOjE3Mjg4ODkwMjR9.pezsDTb9_1JfOhO2OtEMJWAhu_ql3kKAcH6kg3ErBp8

{
    "product_name": "example product 2",
    "product_thumb": "example",
    "product_description": "day chuyen chu dai bi",
    "product_price": 2000,
    "product_quantity": 10,
    "product_type": "Clothing",
    "product_shop": "66a31ae40e5d5b78e6fd8a58",
    "product_attributes": {"manufactuer": "Sxx", "size": "XXL", "material": "String"}
}

###
GET {{url_dev}}/product/draft/all
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyMTM2NjI0LCJleHAiOjE3MjIzMDk0MjR9.4vaq8lvm_087ulyFiuUK3_GsmHVCUGtj5nMKmbC95WA


###
GET {{url_dev}}/product/public/all
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyOTI2MDIxLCJleHAiOjE3MjMwOTg4MjF9.JNvMUuW__mydvxNH6lMVXCGEa_sjVJCrgeNWgIzD3pU


###
PATCH {{url_dev}}/product/public/66b1c3e47b7e4a56e762a4ec
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyOTI2MDIxLCJleHAiOjE3MjMwOTg4MjF9.JNvMUuW__mydvxNH6lMVXCGEa_sjVJCrgeNWgIzD3pU

###
PATCH {{url_dev}}/product/un-public/66a5bfcfe7aea184f1184c16
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyMTM2NjI0LCJleHAiOjE3MjIzMDk0MjR9.4vaq8lvm_087ulyFiuUK3_GsmHVCUGtj5nMKmbC95WA

###
GET {{url_dev}}/product/search/12
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyMTM2NjI0LCJleHAiOjE3MjIzMDk0MjR9.4vaq8lvm_087ulyFiuUK3_GsmHVCUGtj5nMKmbC95WA


###
GET {{url_dev}}/product/
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyMTM2NjI0LCJleHAiOjE3MjIzMDk0MjR9.4vaq8lvm_087ulyFiuUK3_GsmHVCUGtj5nMKmbC95WA

### Get List Public Product by User
GET {{url_dev}}/product/66a5bfcfe7aea184f1184c16
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyMTM2NjI0LCJleHAiOjE3MjIzMDk0MjR9.4vaq8lvm_087ulyFiuUK3_GsmHVCUGtj5nMKmbC95WA


### update Product
PATCH {{url_dev}}/product/66a5bfcfe7aea184f1184c16
Content-Type: application/json
x-api-key: baonguyen
x-client-id: 66a5b830837f0697ccebba73
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmE1YjgzMDgzN2YwNjk3Y2NlYmJhNzMiLCJlbWFpbCI6ImV4YW1wbGUxMjNAZ21haWwuY29tIiwiaWF0IjoxNzIyMzk1NDM2LCJleHAiOjE3MjI1NjgyMzZ9.xorQokMoN7K-hYmLW16Gbe0XUnlY3WG31zgAfGt79S4

{
    "product_type" : "Clothing",
    "product_name": "",
    "product_description": [],
    "product_price": 2000,
    "product_attributes": {"brand": {}, "size": null, "material": ""}
}